# Generated by Django 5.2.1 on 2025-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
