# Generated by Django 5.2.1 on 2025-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='new_email_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='new_email_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
