# Generated by Django 5.2.1 on 2025-06-09 13:52

import narma.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverificationcode_new_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[narma.utils.image_validators.validate_image_size, narma.utils.image_validators.validate_image_resolution]),
        ),
    ]
