# Generated by Django 5.2.1 on 2025-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendrequest_unique_together_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
